In [1]:
import pandas as pd
from datetime import datetime as dt
from datetime import timedelta

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
fcstdate = "20240520"

depdates = []
depdate = "20240520"
while depdate <= "20250517":
    depdates.append(depdate)
    depdate = dt.strftime(dt.strptime(depdate, "%Y%m%d") + timedelta(days=1), "%Y%m%d")

# Read fdc files

In [ ]:
fdc_dfs = None
for depdate in depdates:
    fname = "s3://ay-emr-job/nrm/fdc/{}/{}/{}/fdc_{}_{}.csv.gz".format(fcstdate[:4], fcstdate[4:6], fcstdate[6:8], fcstdate, depdate)
    df = pd.read_csv(fname, low_memory = False)
    if fdc_dfs is None:
        fdc_dfs = [df] 
    else:
        fdc_dfs.append(df)
    print(depdate, end=" ")
fdc_df = pd.concat(fdc_dfs)

20240520 20240521 20240522 20240523 20240524 20240525 20240526 20240527 20240528 20240529 20240530 20240531 20240601 20240602 20240603 20240604 20240605 20240606 20240607 20240608 20240609 20240610 20240611 20240612 20240613 20240614 20240615 20240616 20240617 20240618 20240619 20240620 20240621 20240622 20240623 20240624 20240625 20240626 20240627 20240628 20240629 20240630 20240701 20240702 20240703 20240704 20240705 20240706 20240707 20240708 20240709 20240710 20240711 20240712 20240713 20240714 20240715 20240716 20240717 20240718 20240719 20240720 20240721 20240722 20240723 20240724 20240725 20240726 20240727 20240728 20240729 20240730 20240731 20240801 20240802 20240803 20240804 20240805 20240806 20240807 20240808 20240809 20240810 20240811 20240812 20240813 20240814 20240815 20240816 20240817 20240818 20240819 20240820 20240821 20240822 20240823 20240824 20240825 20240826 20240827 20240828 20240829 20240830 20240831 20240901 20240902 20240903 20240904 20240905 20240906 20240907 20240908 20240909 20240910 20240911 20240912 20240913 20240914 20240915 20240916 20240917 20240918 20240919 20240920 20240921 20240922 20240923 20240924 20240925 20240926 20240927 20240928 20240929 20240930 20241001 20241002 20241003 20241004 20241005 20241006 20241007 20241008 20241009 20241010 20241011 20241012 20241013 20241014 20241015 20241016 20241017 20241018 20241019 20241020 20241021 20241022 20241023 20241024 20241025 20241026 20241027 20241028 20241029 20241030 20241031 20241101 20241102 20241103 20241104 20241105 20241106 20241107 20241108 20241109 20241110 20241111 20241112 20241113 20241114 20241115 20241116 20241117 20241118 20241119 20241120 20241121 20241122 20241123 20241124 20241125 20241126 20241127 20241128 20241129 20241130 20241201 20241202 20241203 20241204 20241205 20241206 20241207

# Read constrained forecast

In [3]:
cf_df = None
for depdate in depdates:
    fname = "s3://ay-emr-job/nrm/cf/{}/{}/{}/cf_{}_{}.csv.gz".format(fcstdate[:4], fcstdate[4:6], fcstdate[6:8], fcstdate, depdate)
    df = pd.read_csv(fname, low_memory = False)
    if cf_df is None:
        cf_df = df 
    else:
        cf_df = pd.concat([cf_df, df])
    print(depdate, end=" ")

20240520 20240521 20240522 20240523 20240524 20240525 20240526 20240527 20240528 20240529 20240530 20240531 20240601 20240602 20240603 20240604 20240605 20240606 20240607 20240608 20240609 20240610 20240611 20240612 20240613 20240614 20240615 20240616 20240617 20240618 20240619 20240620 20240621 20240622 20240623 20240624 20240625 20240626 20240627 20240628 20240629 20240630 20240701 20240702 20240703 20240704 20240705 20240706 20240707 20240708 20240709 20240710 20240711 20240712 20240713 20240714 20240715 20240716 20240717 20240718 20240719 20240720 20240721 20240722 20240723 20240724 20240725 20240726 20240727 20240728 20240729 20240730 20240731 20240801 20240802 20240803 20240804 20240805 20240806 20240807 20240808 20240809 20240810 20240811 20240812 20240813 20240814 20240815 20240816 20240817 20240818 20240819 20240820 20240821 20240822 20240823 20240824 20240825 20240826 20240827 20240828 20240829 20240830 20240831 20240901 20240902 20240903 20240904 20240905 20240906 20240907 20240908 20240909 20240910 20240911 20240912 20240913 20240914 20240915 20240916 20240917 20240918 20240919 20240920 20240921 20240922 20240923 20240924 20240925 20240926 20240927 20240928 20240929 20240930 20241001 20241002 20241003 20241004 20241005 20241006 20241007 20241008 20241009 20241010 20241011 20241012 20241013 20241014 20241015 20241016 20241017 20241018 20241019 20241020 20241021 20241022 20241023 20241024 20241025 20241026 20241027 20241028 20241029 20241030 20241031 20241101 20241102 20241103 20241104 20241105 20241106 20241107 20241108 20241109 20241110 20241111 20241112 20241113 20241114 20241115 20241116 20241117 20241118 20241119 20241120 20241121 20241122 20241123 20241124 20241125 20241126 20241127 20241128 20241129 20241130 20241201 20241202 20241203 20241204 20241205 20241206 20241207 20241208 20241209 20241210 20241211 20241212 20241213 20241214 20241215 20241216 20241217 20241218 20241219 20241220 20241221 20241222 20241223 20241224 20241225 20241226 20241227 20241228 20241229 20241230 20241231 20250101 20250102 20250103 20250104 20250105 20250106 20250107 20250108 20250109 20250110 20250111 20250112 20250113 20250114 20250115 20250116 20250117 20250118 20250119 20250120 20250121 20250122 20250123 20250124 20250125 20250126 20250127 20250128 20250129 20250130 20250131 20250201 20250202 20250203 20250204 20250205 20250206 20250207 20250208 20250209 20250210 20250211 20250212 20250213 20250214 20250215 20250216 20250217 20250218 20250219 20250220 20250221 20250222 20250223 20250224 20250225 20250226 20250227 20250228 20250301 20250302 20250303 20250304 20250305 20250306 20250307 20250308 20250309 20250310 20250311 20250312 20250313 20250314 20250315 20250316 20250317 20250318 20250319 20250320 20250321 20250322 20250323 20250324 20250325 20250326 20250327 20250328 20250329 20250330 20250331 20250401 20250402 20250403 20250404 20250405 20250406 20250407 20250408 20250409 20250410 20250411 20250412 20250413 20250414 20250415 20250416 20250417 20250418 20250419 20250420 20250421 20250422 20250423 20250424 20250425 20250426 20250427 20250428 20250429 20250430 20250501 20250502 20250503 20250504 20250505 20250506 20250507 20250508 20250509 20250510 20250511 20250512 20250513 20250514 20250515 20250516 20250517

In [6]:
cf_df[(cf_df["BASE_OD_ORGN"] == "JFK") & (cf_df["BASE_OD_DSTN"] == "TLL") & (cf_df["POS"] == "US")].head(5)

Empty DataFrame
Columns: [GEO_OD_TS_KEY, BASE_OD_ORGN, BASE_OD_DSTN, BASE_OD_VIA, BASE_OD_ORGN_COUNTRY, BASE_OD_ORGN_REGION, BASE_OD_DSTN_COUNTRY, BASE_OD_DSTN_REGION, BASE_OPR_CC, BASE_OPR_FLTNUM, BASE_MKT_CC, BASE_MKT_FLTNUM, BASE_OD_DEPT_DATE, BASE_SEG_DEP_DATE, BASE_SEG_ARR_DATE, GEO_ORGN, GEO_DSTN, PREV_VIA, PREV_OPR_CC, PREV_OPR_FLTNUM, PREV_MKT_CC, PREV_MKT_FLTNUM, PREV_SEG_DEP_DATE, PREV_SEG_ARR_DATE, NEXT_VIA, NEXT_OPR_CC, NEXT_OPR_FLTNUM, NEXT_MKT_CC, NEXT_MKT_FLTNUM, NEXT_SEG_DEP_DATE, NEXT_SEG_ARR_DATE, POS, BC, FF, TP, MP, D, LPS, SRC_DATE]
Index: []

# Read NRV PWL values

In [3]:
nrv_pwl_df = None
for depdate in depdates:
    fname = "s3://ay-emr-job/nrm/nrv_pwl/{}/{}/{}/nrv_pwl_{}_{}.csv.gz".format(fcstdate[:4], fcstdate[4:6], fcstdate[6:8], fcstdate, depdate)
    df = pd.read_csv(fname, low_memory = False)
    if df is None:
        nrv_pwl_df = df 
    else:
        nrv_pwl_df = pd.concat([nrv_pwl_df, df])

In [5]:
df.head(5)

,GEO_OD_TS_KEY,GEO_ORGN,GEO_DSTN,BASE_OD_ORGN,BASE_OD_ORGN_COUNTRY,BASE_OD_DSTN,BASE_OD_DSTN_COUNTRY,BASE_OD_DEPT_DATE,POS,FF,GFF,TP,NRV,SRC_DATE
0,ABZBGO2024051920240519WF0399BGOHEL202405202024...,ABZ,HEL,BGO,NO,HEL,FI,20240520,GB,EEYL,ECOL,B,396.940890,20240520
1,ABZBGO2024051920240519WF0399BGOHEL202405202024...,ABZ,HEL,BGO,NO,HEL,FI,20240520,GB,EEYL,ECOL,L,145.426674,20240520
2,AGPHEL2024052020240520AY1676,AGP,HEL,AGP,ES,HEL,FI,20240520,ES,EEJ,BUS,B,398.163636,20240520
3,AGPHEL2024052020240520AY1676,AGP,HEL,AGP,ES,HEL,FI,20240520,ES,EEJ,BUS,L,349.594313,20240520
4,AGPHEL2024052020240520AY1676,AGP,HEL,AGP,ES,HEL,FI,20240520,ES,EEYL,ECOL,B,313.754269,20240520

In [7]:
df[(df["BASE_OD_ORGN"] == "JFK") & (df["BASE_OD_DSTN"] == "TLL") & (df["POS"] == "US")]["BASE_OD_DEPT_DATE"].unique()

array([], dtype=int64)