In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("s3://ay-emr-job/nrm/nrv_pwl/2024/05/06/nrv_pwl_20240506_20241028.csv.gz")

In [8]:
df[
    (df["BASE_OD_ORGN"] == "FUE") &
    (df["BASE_OD_DSTN"] == "HEL")
].head(5)

,GEO_OD_TS_KEY,BASE_OD_ORGN,BASE_OD_DSTN,BASE_OD_VIA,BASE_OD_ORGN_COUNTRY,BASE_OD_ORGN_REGION,BASE_OD_DSTN_COUNTRY,BASE_OD_DSTN_REGION,BASE_OPR_CC,BASE_OPR_FLTNUM,...,NEXT_SEG_DEP_DATE,NEXT_SEG_ARR_DATE,POS,BC,FF,TP,MP,D,LPS,SRC_DATE
61360,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,NaN,NaN,ES,Y,EEYL,B,652.000000,0.065074,0.065074,20240506
61361,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,NaN,NaN,ES,B,EEYL,B,522.578753,0.023437,0.023437,20240506
61362,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,NaN,NaN,ES,H,EEYL,B,418.113594,0.025338,0.025338,20240506
61363,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,NaN,NaN,ES,K,EEYL,B,261.617010,0.037983,0.037983,20240506
61364,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,NaN,NaN,ES,M,EEYL,B,147.533516,0.031754,0.031754,20240506

In [6]:
df = pd.read_csv("s3://ay-emr-job/nrm/cf/2024/05/06/cf_20240506_20241028.csv.gz", low_memory=False)

In [9]:
df[
    (df["BASE_OD_ORGN"] == "FUE") &
    (df["BASE_OD_DSTN"] == "HEL")
].head(5)

,GEO_OD_TS_KEY,BASE_OD_ORGN,BASE_OD_DSTN,BASE_OD_VIA,BASE_OD_ORGN_COUNTRY,BASE_OD_ORGN_REGION,BASE_OD_DSTN_COUNTRY,BASE_OD_DSTN_REGION,BASE_OPR_CC,BASE_OPR_FLTNUM,...,NEXT_SEG_DEP_DATE,NEXT_SEG_ARR_DATE,POS,BC,FF,TP,MP,D,LPS,SRC_DATE
61360,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,NaN,NaN,ES,Y,EEYL,B,652.000000,0.065074,0.065074,20240506
61361,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,NaN,NaN,ES,B,EEYL,B,522.578753,0.023437,0.023437,20240506
61362,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,NaN,NaN,ES,H,EEYL,B,418.113594,0.025338,0.025338,20240506
61363,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,NaN,NaN,ES,K,EEYL,B,261.617010,0.037983,0.037983,20240506
61364,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,NaN,NaN,ES,M,EEYL,B,147.533516,0.031754,0.031754,20240506

In [18]:
df = pd.read_csv("s3://ay-emr-job/nrm/fdc/2024/05/06/fdc_20240506_20241028.csv.gz", low_memory=False)

In [19]:
df[
    (df["BASE_OD_ORGN"] == "FUE") &
    (df["BASE_OD_DSTN"] == "HEL") &
    (df["BASE_OD_DEP_DATE"] == 20241028)
].head(5)

,GEO_OD_TS_KEY,BASE_OD_ORGN,BASE_OD_DSTN,BASE_OD_VIA,BASE_OD_ORGN_COUNTRY,BASE_OD_ORGN_REGION,BASE_OD_DSTN_COUNTRY,BASE_OD_DSTN_REGION,BASE_OPR_CC,BASE_OPR_FLTNUM,...,BC,FF,TP,SMPWA,AMPWA,SRD,ARD,SFD,AFD,SRC_DATE
216476,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,A,NaN,B,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,20240429
216477,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,A,NaN,L,216.00000,0.000000,1.021751,0.000000,1.243462,0.000000,20240429
216478,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,Y,EEYL,B,652.00000,652.000000,0.104573,0.065074,0.109119,0.068076,20240429
216479,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,Y,EEYL,L,652.00000,652.000000,1.114219,0.755960,1.175371,0.804175,20240429
216480,FUEHEL2024102820241028AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,B,EEYL,B,439.33223,522.578753,0.055852,0.023437,0.058462,0.024591,20240429

In [20]:
df = pd.read_csv("s3://ay-emr-job/nrm/bff/2024/05/06/FCST_OD_20240506_20241028.csv.gz", low_memory=False)

In [21]:
df[
    (df["BASE_OD_ORGN"] == "FUE") &
    (df["BASE_OD_DSTN"] == "HEL") &
    (df["BASE_OD_DEP_DATE"] == 20241028)
].head(5)

,GEO_OD_TS_KEY,BASE_OD_ORGN,BASE_OD_DSTN,BASE_OD_VIA,BASE_OD_ORGN_COUNTRY,BASE_OD_ORGN_REGION,BASE_OD_DSTN_COUNTRY,BASE_OD_DSTN_REGION,BASE_OPR_CC,BASE_OPR_FLTNUM,...,SRGCCD,SGCD,SRGCD,AFD,ARD,ARDSUM,ARGCCD,AGCD,ARGCD,SRC_DATE
217442,FUEHEL2024102820241029AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,0.000000,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,20240506
217443,FUEHEL2024102820241029AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,1.058680,1.05868,0.0,0.000000,0.000000,0.000000,0.000000,1.05868,0.0,20240506
217444,FUEHEL2024102820241029AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,0.122162,0.00000,0.0,0.077301,0.076768,0.076767,0.076767,0.00000,0.0,20240506
217445,FUEHEL2024102820241029AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,1.123159,0.00000,0.0,0.793512,0.772848,0.772848,0.772848,0.00000,0.0,20240506
217446,FUEHEL2024102820241029AY1702,FUE,HEL,NaN,ES,EUROPE,FI,EUROPE,AY,1702,...,0.063490,0.00000,0.0,0.027167,0.026879,0.026878,0.026878,0.00000,0.0,20240506